services:
  kafka1:
    ports:
      - "19096:9097"
    environment:
      KAFKA_LISTENERS: BROKER://kafka1:9092,EXTERNAL://kafka1:9094,CONTROLLER://kafka1:9093,SASL_INTERNAL://kafka1:9096,SASL_EXTERNAL://kafka1:9097
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:9092,EXTERNAL://localhost:9094,SASL_INTERNAL://kafka1:9096,SASL_EXTERNAL://localhost:19096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,SASL_INTERNAL:SASL_PLAINTEXT,SASL_EXTERNAL:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_LISTENER_NAME_SASL_INTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_LISTENER_NAME_SASL_EXTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_LISTENER_NAME_SASL_INTERNAL_SCRAM_SHA_512_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required;
      KAFKA_LISTENER_NAME_SASL_EXTERNAL_SCRAM_SHA_512_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required;
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_SUPER_USERS: User:admin
    volumes:
      - ./conf/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro
