version: '3.5'

networks:
  kafkaworkshop:
    name: kafkaworkshop
services:
  kafka1:
    image: confluentinc/cp-kafka:7.5.2
    hostname: kafka1
    container_name: kafka1
    environment:
      KAFKA_LISTENERS: BROKER://kafka1:9092,EXTERNAL://kafka1:9094,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: KUQll_wsRdWF7yPPb85xNA
    ports:
      - "9094:9094"
    networks:
      - kafkaworkshop
    volumes:
      - kafka1-data:/var/lib/kafka/data

  schemaregistry:
    image: confluentinc/cp-schema-registry:7.5.2
    container_name: schemaregistry
    restart: always
    depends_on:
      - kafka1
    networks:
      - kafkaworkshop
    ports:
      - "8085:8085"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085

volumes:
  kafka1-data:
