
networks:
  kafkaworkshop:
    name: kafkaworkshop
services:
  kafka1:
    image: confluentinc/cp-kafka:7.5.2
    hostname: kafka1
    container_name: kafka1
    environment:
      KAFKA_LISTENERS: BROKER://kafka1:9092,EXTERNAL://kafka1:9094,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: KUQll_wsRdWF7yPPb85xNA
    ports:
      - "9094:9094"
    networks:
      - kafkaworkshop
    volumes:
      - kafka1-data:/var/lib/kafka/data

  schemaregistry:
    image: confluentinc/cp-schema-registry:7.5.2
    hostname: schemaregistry
    container_name: schemaregistry
    restart: always
    depends_on:
      - kafka1
    networks:
      - kafkaworkshop
    ports:
      - "8085:8085"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085

  kafkaconnect:
    image: confluentinc/cp-kafka-connect:7.4.3
    restart: always
    hostname: kafkaconnect
    container_name: kafkaconnect
    ports:
      - "8083:8083"
    volumes:
      - kc-data:/data
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka1:9092
      CONNECT_GROUP_ID: "kafka-connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "_kafka-connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "_kafka-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "_kafka-connect-status"
      CONNECT_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"

      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schemaregistry:8085"

      CONNECT_REST_ADVERTISED_HOST_NAME: "kafkaconnect"
      CONNECT_LISTENERS: http://kafkaconnect:8083
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

      # Connect worker
      CONNECT_SECURITY_PROTOCOL: PLAINTEXT

      # Connect producer
      CONNECT_PRODUCER_SECURITY_PROTOCOL: PLAINTEXT

      # Connect consumer
      CONNECT_CONSUMER_SECURITY_PROTOCOL: PLAINTEXT

    depends_on:
      - kafka1
      - schemaregistry
      - postgres
    networks:
      - kafkaworkshop

    command:
      - bash
      - -c
      - |
        echo "Installing Connector"
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.0
        #
        echo "Launching Kafka Connect worker" 
        /etc/confluent/docker/run &
        #
        sleep infinity

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres17-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=workshop

    networks:
      - kafkaworkshop

volumes:
  kafka1-data:
  kc-data:
  postgres17-data:
