app:
  kafka:
    bootstrapServer: "kafka-workshop-001-kafka-workshop.aivencloud.com:13816"
    securityProtocol: "SASL_SSL"
    schemaRegistryUrl: "https://kafka-workshop-001-kafka-workshop.aivencloud.com:13806"
    schemaRegistryBasicAuth: ${SCHEMA_REG_BASIC_AUTH}
    saslUsername: ${SASL_USERNAME}
    saslPassword: ${SASL_PASSWORD}
    avroSerializableClasses:
      - "io.bekk.publisher.WorkshopStatusMessage"
server:
  port: ${PORT:3000}
