app:
  cors: ${CORS_ALLOWED_ORIGINS:http://localhost:3001/;http://localhost:3000;http://localhost:3003}
  kafka:
    bootstrapServer: "localhost:9092"
    securityProtocol: "PLAINTEXT"
    schemaRegistryUrl: "http://localhost:8001/"
server:
  port: ${PORT:3000}
